Repository Pack-Smart/pack-smart-fe, pull requests merged in 2021-03, with the labels that each got.

#96 Optimize/update trip details modal
  src/ListThumbnail/ListThumbnail.scss
  src/PackingList/PackingList.scss
  src/QuestionInput/QuestionInput.js
  src/QuestionInput/QuestionInput.scss
  src/Quiz/Quiz.scss
  src/UpdateDetailsModal/UpdateDetailsModal.js
  src/UpdateDetailsModal/UpdateDetailsModal.scss
  src/UpdateDetailsModal/modalData.js
  src/mixins.scss
Labels: Frontend, Phase 4, styles

#98 Feature/delete item api call
  src/PackingList/PackingList.js
  src/Quiz/Quiz.js
  src/SavedView/SavedView.js
  src/StaticItem/StaticItem.js
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/apiCalls.js
Labels: API, Frontend, Phase 4, feature, refactor

#97 Phase4 cleanup
  public/favicon.png
  src/Error/Error.js
  src/Error/Error.scss
  src/Hamburger/Hamburger.js
  src/Hamburger/Hamburger.scss
  src/Hamburger/mobileMenuData.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Home/Home.js
  src/Home/Home.scss
  src/Home/beachBackground.jpeg
  src/Home/campingBackground.jpg
  src/Home/cityBackground.jpg
  src/Home/mountainsBackground.jpg
  src/ListThumbnail/ListThumbnail.scss
  src/MultipleChoice/MultipleChoice.scss
  src/PackingList/PackingList.js
  src/PackingList/PackingList.scss
  src/QuestionInput/QuestionInput.scss
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/SavedView/SavedView.js
  src/SavedView/SavedView.scss
  src/StaticCategory/StaticCategory.js
  src/StaticCategory/StaticCategory.scss
  src/StaticCategory/categoryIcons.js
  src/StaticItem/StaticItem.js
  src/StaticItem/StaticItem.scss
  src/UpdateDetailsModal/UpdateDetailsModal.js
  src/UpdateDetailsModal/UpdateDetailsModal.scss
  src/VerifyDeletionModal/VerifyDeletionModal.scss
Labels: Frontend, Phase 4, styles

#100 Feature/saved list verify deletion modal
  src/Error/Error.scss
  src/ListThumbnail/ListThumbnail.js
  src/PackingList/PackingList.js
  src/SavedView/SavedView.js
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/VerifyDeletionModal/modalStyles.js
Labels: Frontend, feature

#101 Testing/redux
  src/actions/actions.test.js
  src/reducers/index.js
  src/reducers/packingList.test.js
  src/reducers/userInfo.test.js
  src/sampleData.js
Labels: Final Phase, Phase 1, Phase 2, Phase 3, Phase 4, pull request, redux, testing

#104 Refactor/categories
  src/Quiz/Quiz.js
  src/Quiz/quizDetails.js
Labels: Frontend, Phase 5, refactor

#106 Refactor/redux connect
  src/App/App.js
  src/ListThumbnail/ListThumbnail.js
  src/Quiz/Quiz.js
  src/StaticItem/StaticItem.js
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/apiCalls.js
Labels: Frontend, Phase 5, bug, fix, refactor

#107 Testing/fetches
  src/ListThumbnail/ListThumbnail.js
  src/PackingList/PackingList.js
  src/Quiz/Quiz.js
  src/SavedView/SavedView.js
  src/StaticItem/StaticItem.js
  src/UpdateDetailsModal/UpdateDetailsModal.js
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/apiCalls/apiCalls.js
  src/apiCalls/apiCalls.test.js
  src/sampleData.js
Labels: API, Phase 5, pull request, styles

#108 Refactor/quiz api calls
  src/PackingList/PackingList.js
  src/Quiz/Quiz.js
  src/SavedView/SavedView.scss
Labels: Frontend, Phase 4, fix, refactor

#111 Refactor/utilities
  src/ListThumbnail/ListThumbnail.js
  src/Quiz/Quiz.js
  src/SavedView/SavedView.js
  src/sampleData.js
  src/utilities/utilities.js
  src/utilities/utilities.test.js
Labels: Phase 5, refactor, testing

#119 Styles/home page
  src/Home/Home.js
  src/Home/Home.scss
  src/Home/backgroundStyle.js
  src/Home/images/background0.jpg
  src/Home/images/background1.jpg
  src/Home/images/background10.jpg
  src/Home/images/background11.jpg
  src/Home/images/background12.jpg
  src/Home/images/background13.jpg
  src/Home/images/background14.jpg
  src/Home/images/background15.jpg
  src/Home/images/background16.jpg
  src/Home/images/background17.jpg
  src/Home/images/background18.jpg
  src/Home/images/background19.jpg
  src/Home/images/background2.jpg
  src/Home/images/background20.jpg
  src/Home/images/background21.jpg
  src/Home/images/background22.jpg
  src/Home/images/background23.jpg
  src/Home/images/background24.jpg
  src/Home/images/background25.jpg
  src/Home/images/background26.jpg
  src/Home/images/background27.jpg
  src/Home/images/background28.jpg
  src/Home/images/background29.jpg
  src/Home/images/background3.jpg
  src/Home/images/background30.jpg
  src/Home/images/background31.jpg
  src/Home/images/background32.jpg
  src/Home/images/background33.jpg
  src/Home/images/background34.jpg
  src/Home/images/background35.jpg
  src/Home/images/background36.jpg
  src/Home/images/background37.jpg
  src/Home/images/background38.jpg
  src/Home/images/background39.jpg
  src/Home/images/background4.jpg
  src/Home/images/background40.jpg
  src/Home/images/background41.jpg
  src/Home/images/background42.jpg
  src/Home/images/background43.jpg
  src/Home/images/background44.jpg
  src/Home/images/background45.jpg
  src/Home/images/background46.jpg
  src/Home/images/background47.jpg
  src/Home/images/background48.jpg
  src/Home/images/background49.jpg
  src/Home/images/background5.jpg
  src/Home/images/background6.jpg
  src/Home/images/background7.jpg
  src/Home/images/background8.jpg
  src/Home/images/background9.jpg
  src/Home/images/imageData.js
  src/PackingList/PackingList.js
  src/PackingList/PackingList.scss
Labels: Frontend, Phase 5, styles

#120 Test cypress/saved list/so
  .nyc_output/out.json
  cypress.json
  cypress/fixtures/example.json
  cypress/fixtures/getPackingListData.json
  cypress/fixtures/getSinglePackingList.json
  cypress/fixtures/saveNewPackingList.json
  cypress/integration/quiz.spec.js
  cypress/integration/saved_list.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/Header/Header.js
  src/Quiz/Quiz.js
  src/SearchList/SearchList.js
  src/SearchList/SearchList.scss
  src/utilities/utilities.js
Labels: testing

#121 Test/cypress packing list
  cypress/integration/categories.spec.js
  src/Home/Home.scss
  src/HowItWorks/howItWorksData.js
Labels: Phase 5, testing

#125 Test/cypress edit details modal
  cypress/fixtures/patchTripDetails.json
  cypress/integration/edit_trip_details.spec.js
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/UpdateDetailsModal/UpdateDetailsModal.js
  src/UpdateDetailsModal/UpdateDetailsModal.scss
  src/mixins.scss
Labels: Phase 5, testing

#124 Test/cypress headers kc
  cypress/integration/hamburger.spec.js
  cypress/integration/header.spec.js
  cypress/integration/quiz.spec.js
  src/Header/Header.js
  src/Header/headerData.js
  src/utilities/utilities.js
Labels: Frontend, Phase 5, testing

#126 Test/cypress save lists so
  cypress/fixtures/deletePackingList.json
  cypress/fixtures/getAllPackingLists.json
  cypress/fixtures/getNoPackingLIsts.json
  cypress/integration/saved_list.spec.js
  src/HowItWorks/HowItWorks.scss
  src/VerifyDeletionModal/VerifyDeletionModal.js
Labels: Frontend, Phase 5, testing

#127 Style cleanup
  public/index.html
  src/Hamburger/Hamburger.js
  src/Header/Header.js
  src/Home/Home.js
  src/Home/Home.scss
  src/Home/images/background16.jpg
  src/Home/images/background21.jpg
  src/Home/images/background23.jpg
  src/Home/images/background42.jpg
  src/Home/images/background47.jpg
  src/Home/images/background50.jpg
  src/Home/images/background51.jpg
  src/Home/images/background52.jpg
  src/Home/images/background53.jpg
  src/Home/images/background54.jpg
  src/Home/images/background55.jpg
  src/Home/images/background56.jpg
  src/Home/images/background57.jpg
  src/Home/images/imageData.js
  src/HowItWorks/HowItWorks.scss
  src/MultipleChoice/MultipleChoice.js
  src/Quiz/Quiz.js
  src/SavedView/SavedView.scss
  src/mixins.scss
Labels: Frontend, fix, styles

#128 remove console log
  src/Quiz/Quiz.js
Labels: fix

#129 reverse dropdown arrows and bring back button outline on focus
  src/StaticCategory/StaticCategory.js
  src/StaticCategory/StaticCategory.scss
Labels: fix, styles

#131 Fix/patch item
  src/Quiz/quizDetails.js
  src/StaticItem/StaticItem.js
Labels: Frontend, bug

#133 Feature/add custom item
  src/AddItemModal/AddItemModal.js
  src/AddItemModal/AddItemModal.scss
  src/AddItemModal/addItemData.js
  src/PackingList/PackingList.js
  src/QuestionInput/QuestionInput.scss
  src/StaticCategory/StaticCategory.js
  src/StaticItem/StaticItem.js
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/apiCalls/apiCalls.js
  src/sampleData.js
  src/utilities/utilities.js
  src/utilities/utilities.test.js
Labels: Phase 6, enhancement, feature
