Repository Pack-Smart/pack-smart-fe, pull requests merged in 2021-02, with the labels that each got.

#4 Project setup
  README.md
  src/App.js
  src/App.test.js
  src/App/App.js
  src/App/App.scss
  src/EditCategory/EditCategory.js
  src/EditCategory/EditCategory.scss
  src/EditItem/EditItem.js
  src/EditItem/EditItem.scss
  src/EditList/EditList.js
  src/EditList/EditList.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Home/Home.js
  src/Home/Home.scss
  src/ListThumbnail/ListThumbnail.js
  src/ListThumbnail/ListThumbnail.scss
  src/PackingList/PackingList.js
  src/PackingList/PackingList.scss
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/SavedView/SavedView.js
  src/SavedView/SavedView.scss
  src/SearchList/SearchList.js
  src/SearchList/SearchList.scss
  src/StaticCategory/StaticCategory.js
  src/StaticCategory/StaticCategory.scss
  src/StaticItem/StaticItem.js
  src/StaticItem/StaticItem.scss
  src/index.scss
  src/mixins.scss
  src/variables.scss
Labels: Frontend, Phase 1, pull request

#8 Feature/landing page
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.scss
  src/Error/Error.js
  src/Error/Error.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Header/cases.png
  src/Home/Home.js
  src/Home/Home.scss
  src/Home/lady.png
  src/index.js
  src/index.scss
  src/mixins.scss
  src/variables.scss
Labels: Frontend, Phase 1, pull request

#9 Feature/quiz UI
  src/App/App.js
  src/Error/Error.js
  src/Error/Error.scss
  src/Header/Header.scss
  src/PackingList/PackingList.js
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/mixins.scss
Labels: Frontend, component, feature

#17 Feature/quiz local state
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
Labels: Phase 1, feature, pull request

#19 Feature/packing list
  package-lock.json
  package.json
  public/index.html
  src/App/App.js
  src/App/App.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Home/Home.js
  src/Home/Home.scss
  src/PackingList/PackingList.js
  src/PackingList/PackingList.scss
  src/SavedView/SavedView.js
  src/StaticCategory/StaticCategory.js
  src/StaticCategory/StaticCategory.scss
  src/StaticCategory/categoryIcons.js
  src/StaticItem/StaticItem.js
  src/StaticItem/StaticItem.scss
  src/mixins.scss
  src/sampleData.js
  src/variables.scss
Labels: Frontend, component, enhancement, feature

#22 Feature/multiple choice
  src/MultipleChoice/MultipleChoice.js
  src/MultipleChoice/MultipleChoice.scss
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/Quiz/quizDetails.js
Labels: Frontend, component, enhancement, refactor, styles

#25 Feature/api contract setup
  src/App/App.js
  src/Quiz/Quiz.js
  src/apiCalls.js
Labels: API, feature

#28 Refactor/quiz inputs
  src/QuestionInput/QuestionInput.js
  src/QuestionInput/QuestionInput.scss
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
Labels: Frontend, Phase 1, pull request, refactor

#37 Feature/get packing results
  package-lock.json
  package.json
  src/App/App.js
  src/Error/Error.js
  src/PackingList/PackingList.js
  src/QuestionInput/QuestionInput.js
  src/Quiz/Quiz.js
  src/Quiz/quizDetails.js
  src/StaticCategory/StaticCategory.js
  src/StaticCategory/categoryIcons.js
  src/StaticItem/StaticItem.js
  src/actions/actions.js
  src/apiCalls.js
  src/index.js
  src/reducers/index.js
  src/reducers/reducers.js
Labels: API, Frontend, error handling, feature

#40 Refactor/quiz UI
  src/Header/Header.js
  src/Header/Header.scss
  src/MultipleChoice/MultipleChoice.js
  src/MultipleChoice/MultipleChoice.scss
  src/PackingList/PackingList.js
  src/QuestionInput/QuestionInput.js
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/Quiz/quizDetails.js
Labels: Frontend, Phase 2, refactor

#41 Feature/edit packing list
  package-lock.json
  package.json
  src/PackingList/PackingList.js
  src/PackingList/PackingList.scss
  src/PackingList/modalStyles.js
  src/StaticCategory/StaticCategory.js
  src/StaticCategory/StaticCategory.scss
  src/StaticItem/StaticItem.js
  src/StaticItem/StaticItem.scss
  src/actions/actions.js
  src/reducers/reducers.js
Labels: Frontend, feature

#44 Feature/list thumbnail
  src/ListThumbnail/ListThumbnail.js
  src/ListThumbnail/ListThumbnail.scss
  src/SavedView/SavedView.js
  src/SavedView/SavedView.scss
  src/mixins.scss
Labels: Frontend, component, feature

#46 Feature/verify deletion modal
  src/PackingList/PackingList.js
  src/PackingList/PackingList.scss
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/VerifyDeletionModal/VerifyDeletionModal.scss
Labels: Frontend, component, refactor

#50 Feature/packing list submit
  src/App/App.test.js
  src/Home/Home.js
  src/PackingList/PackingList.js
  src/Quiz/Quiz.js
  src/Quiz/quizDetails.js
  src/actions/actions.js
  src/apiCalls.js
  src/reducers/index.js
  src/reducers/packingList.js
  src/reducers/userInfo.js
Labels: API, Frontend

#51 Feature/update styles
  src/App/App.js
  src/Error/Error.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Home/Home.scss
  src/Home/cases.png
  src/HowItWorks/HowItWorks.js
  src/HowItWorks/HowItWorks.scss
  src/HowItWorks/background.png
  src/ListThumbnail/ListThumbnail.js
  src/ListThumbnail/ListThumbnail.scss
  src/MultipleChoice/MultipleChoice.scss
  src/PackingList/PackingList.scss
  src/PackingList/background.png
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/Quiz/background.png
  src/Review/Review.js
  src/SavedView/SavedView.js
  src/SavedView/SavedView.scss
  src/SavedView/background.png
  src/StaticCategory/StaticCategory.js
  src/StaticCategory/StaticCategory.scss
  src/StaticItem/StaticItem.js
  src/StaticItem/StaticItem.scss
  src/Step/Step.js
  src/Step/Step.scss
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/VerifyDeletionModal/VerifyDeletionModal.scss
  src/apiCalls.js
Labels: Frontend, Phase 3, enhancement, error handling, refactor, styles

#61 Feature/fetch me if you can
  src/ListThumbnail/ListThumbnail.js
  src/ListThumbnail/ListThumbnail.scss
  src/PackingList/PackingList.js
  src/SavedView/SavedView.js
  src/actions/actions.js
  src/apiCalls.js
Labels: API, Frontend, Phase 3, feature

#63 Refactor/initial responsiveness
  package-lock.json
  package.json
  src/Hamburger/Hamburger.js
  src/Hamburger/Hamburger.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Home/Home.js
  src/Home/Home.scss
  src/HowItWorks/HowItWorks.js
  src/HowItWorks/HowItWorks.scss
  src/MultipleChoice/MultipleChoice.js
  src/MultipleChoice/MultipleChoice.scss
  src/QuestionInput/QuestionInput.js
  src/QuestionInput/QuestionInput.scss
  src/Quiz/Quiz.js
  src/Quiz/Quiz.scss
  src/Step/Step.js
  src/Step/Step.scss
  src/mixins.scss
Labels: Frontend, Phase 4, enhancement, styles

#70 Feature/responsive packing list
  src/PackingList/PackingList.js
  src/StaticCategory/StaticCategory.scss
  src/StaticItem/StaticItem.scss
Labels: Frontend, Phase 4, styles

#71 Refactor/organize imports
  src/App/App.js
  src/App/App.test.js
  src/EditCategory/EditCategory.js
  src/EditCategory/EditCategory.scss
  src/EditItem/EditItem.js
  src/EditItem/EditItem.scss
  src/EditList/EditList.js
  src/EditList/EditList.scss
  src/Error/Error.js
  src/Error/Error.scss
  src/Hamburger/Hamburger.js
  src/Header/Header.js
  src/Home/Home.js
  src/HowItWorks/HowItWorks.js
  src/ListThumbnail/ListThumbnail.js
  src/MultipleChoice/MultipleChoice.js
  src/PackingList/PackingList.js
  src/QuestionInput/QuestionInput.js
  src/Quiz/Quiz.js
  src/Quiz/quizDetails.js
  src/Review/Review.js
  src/SavedView/SavedView.js
  src/StaticCategory/StaticCategory.js
  src/StaticItem/StaticItem.js
  src/Step/Step.js
  src/VerifyDeletionModal/VerifyDeletionModal.js
  src/apiCalls.js
  src/index.js
Labels: Frontend, refactor

#75 Refactor/how it works
  src/Header/Header.js
  src/Header/Header.scss
  src/Home/Home.js
  src/Home/Home.scss
  src/Home/cases.png
  src/HowItWorks/HowItWorks.js
  src/HowItWorks/HowItWorks.scss
  src/HowItWorks/howItWorksData.js
  src/ListThumbnail/ListThumbnail.scss
  src/Review/Review.js
  src/SavedView/SavedView.scss
  src/StaticCategory/categoryIcons.js
  src/Step/Step.js
  src/Step/Step.scss
Labels: Frontend, Phase 3, refactor

#74 Refactor/burger
  src/Hamburger/Hamburger.js
  src/Hamburger/Hamburger.scss
  src/Header/Header.js
Labels: Frontend, fix, styles

#78 Feature/thumbnail me if you can
  src/App/App.js
  src/Home/Home.js
  src/ListThumbnail/ListThumbnail.js
  src/ListThumbnail/ListThumbnail.scss
  src/MultipleChoice/MultipleChoice.scss
  src/PackingList/PackingList.js
  src/Quiz/quizDetails.js
  src/SavedView/SavedView.js
  src/apiCalls.js
Labels: API, Frontend, Phase 3, feature, redux, styles

#87 Refactor/UI cleanup phase 4
  public/bw-hearts.jpeg
  public/favicon.ico
  public/favicon.png
  public/hearts-blue.png
  public/index.html
  public/manifest.json
  public/two-hearts.png
  src/Error/Error.scss
  src/Header/Header.scss
  src/HowItWorks/HowItWorks.js
  src/ListThumbnail/ListThumbnail.scss
  src/MultipleChoice/MultipleChoice.scss
  src/PackingList/PackingList.js
  src/QuestionInput/QuestionInput.js
  src/Quiz/Quiz.scss
  src/SavedView/SavedView.js
  src/SavedView/SavedView.scss
  src/Step/Step.scss
  src/VerifyDeletionModal/VerifyDeletionModal.scss
  src/index.scss
  src/mixins.scss
  src/variables.scss
Labels: Phase 4, refactor

#92 Feature/patch me if you can
  src/ListThumbnail/ListThumbnail.js
  src/PackingList/PackingList.js
  src/PackingList/PackingList.scss
  src/PackingList/modalStyles.js
  src/QuestionInput/QuestionInput.js
  src/StaticItem/StaticItem.js
  src/UpdateDetailsModal/UpdateDetailsModal.js
  src/UpdateDetailsModal/UpdateDetailsModal.scss
  src/actions/actions.js
  src/apiCalls.js
  src/reducers/packingList.js
Labels: API, Frontend, Phase 4, component
